import mongoose from "mongoose";

const applicantSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    applicantId: {
      type: String,
      unique: true,
      required: true,
    },
    fullName: String,
    email: String,
    phone: String,
    gender: String,
    dob: String,
    religion: String,
    maritalStatus: String,
    placeOfBirth: String,
    height: String,
    bloodGroup: String,
    genotype: String,
    urinaryTest: String,
    generalAptitudeScore: String,
    vocationalAptitudeScore: String,
    oralTestScore: String,
    documentsPresented: String,
    remarks: String,
    eliteAdminOfficerName: String,
    eliteAdminOfficerPortfolio: String,
    eliteAdminOfficerSignatureDate: String,
    directorateName: String,
    directoratePortfolio: String,
    directorateSignatureDate: String,
    nationality: String,
    profession: String,
    professionAddress: String,
    educationQualification: String,
    disability: String,
    convictedBefore: String,
    convictionReasons: String,
    paramilitaryMember: String,
    paramilitaryName: String,
    paramilitaryRank: String,
    paramilitaryPost: String,
    paramilitaryYears: String,
    leavingReasons: String,
    declarationName: String,
    declarationDate: String,
    state: String,
    lga: String,
    address: String,
    qualification: String,
    kinName: String,
    kinPhone: String,
    medInfo: String,
    whyJoin: String,
    status: {
      type: String,
      enum: ["pending", "under_review", "approved", "rejected"],
      default: "pending",
    },
    serviceStatus: {
      type: String,
      enum: ["active", "dismissed", "retired"],
      default: "active",
    },
    submitted: {
      type: Boolean,
      default: false,
    },
    submittedAt: Date,
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

export default mongoose.model("Applicant", applicantSchema);
